version: "3.9"

networks:
  local:
    name: local

services:
  app:
    container_name: webserver
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - local

  mysql:
    container_name: mysqldb
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pwss
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - local

  phpmyadmin:
    container_name: phpmyadmin-app
    image: phpmyadmin:latest
    restart: always
    ports:
      - "81:80"
    depends_on:
      - mysql
    links:
      - "mysql:db"
    networks:
      - local
